import { Book, BookState } from "@/types/Book";

export const books: Book[] = [
  {
    title: "1984",
    author: "George Orwell",
    initDate: [new Date("2023-01-10")],
    endDate: [new Date("2023-01-20")],
    description: "A dystopian novel about totalitarianism and surveillance.",
    valoration: 5,
    review: "A timeless classic with chilling relevance.",
    quotes: ["Big Brother is watching you."],
    comments: [
      { page: 45, text: "First mention of Big Brother." },
      { page: 123, text: "Winston's rebellion begins." },
    ],
    cover: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
    state: BookState.Read,
    progressPage: 328,
    favourite: true,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    initDate: [new Date("2023-03-05")],
    endDate: [new Date("2023-03-18")],
    description:
      "A story about racial injustice and childhood in the Deep South.",
    valoration: 5,
    review: "Touching and powerful.",
    quotes: [
      "You never really understand a person until you consider things from his point of view.",
    ],
    comments: [
      { page: 89, text: "Atticus’ courtroom speech is unforgettable." },
    ],
    cover: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
    state: BookState.Read,
    progressPage: 281,
    favourite: true,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    initDate: [new Date("2023-04-01")],
    endDate: [new Date("2023-04-15")],
    description: "A fantasy adventure about Bilbo Baggins and a dragon.",
    valoration: 4,
    review: "Charming and adventurous.",
    quotes: ["In a hole in the ground there lived a hobbit."],
    comments: [{ page: 10, text: "Love the whimsical start." }],
    cover: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
    state: BookState.Read,
    progressPage: 310,
    favourite: false,
    saga: "Middle-Earth",
  },
  {
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    initDate: [new Date("2024-01-10")],
    endDate: [new Date("2024-02-02")],
    description: "The first part of The Lord of the Rings.",
    valoration: 5,
    review: "Epic start to the trilogy.",
    quotes: [
      "All we have to decide is what to do with the time that is given us.",
    ],
    comments: [
      { page: 250, text: "Gandalf’s fall in Moria is heartbreaking." },
    ],
    cover: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    state: BookState.Read,
    progressPage: 423,
    favourite: true,
    saga: "The Lord of the Rings",
  },
  {
    title: "The Two Towers",
    author: "J.R.R. Tolkien",
    initDate: [new Date("2024-02-10")],
    endDate: [new Date("2024-03-05")],
    description: "The second part of The Lord of the Rings.",
    valoration: 5,
    review: "The pace picks up. Incredible battles.",
    quotes: ["The battle for Helm’s Deep is about to begin."],
    comments: [{ page: 150, text: "Helm’s Deep descriptions are epic." }],
    cover: "https://covers.openlibrary.org/b/id/8231857-L.jpg",
    state: BookState.Read,
    progressPage: 352,
    favourite: true,
    saga: "The Lord of the Rings",
  },
  {
    title: "The Return of the King",
    author: "J.R.R. Tolkien",
    initDate: [new Date("2024-03-12")],
    endDate: [new Date("2024-04-01")],
    description: "The final part of The Lord of the Rings.",
    valoration: 5,
    review: "A perfect ending.",
    quotes: [
      "I am glad you are here with me. Here at the end of all things, Sam.",
    ],
    comments: [{ page: 400, text: "Emotional farewell." }],
    cover: "https://covers.openlibrary.org/b/id/8231858-L.jpg",
    state: BookState.Read,
    progressPage: 416,
    favourite: true,
    saga: "The Lord of the Rings",
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    initDate: [new Date("2024-05-01")],
    endDate: [],
    description:
      "A science fiction epic about politics, religion, and sandworms.",
    quotes: ["Fear is the mind-killer."],
    comments: [
      { page: 57, text: "Introduction of Arrakis is stunning." },
      { page: 202, text: "Paul starts to show leadership." },
    ],
    cover: "https://covers.openlibrary.org/b/id/8101354-L.jpg",
    state: BookState.Reading,
    progressPage: 280,
    favourite: false,
    saga: "Dune Saga",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    initDate: [new Date("2023-09-01")],
    endDate: [new Date("2023-09-20")],
    description: "A romantic novel of manners.",
    valoration: 4,
    review: "Witty and timeless.",
    quotes: ["It is a truth universally acknowledged..."],
    comments: [{ page: 120, text: "Elizabeth’s wit is unmatched." }],
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    state: BookState.Read,
    progressPage: 279,
    favourite: false,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    initDate: [new Date("2022-11-05")],
    endDate: [new Date("2022-11-15")],
    description: "A novel about teenage alienation.",
    valoration: 3,
    review: "Not my style but interesting.",
    quotes: [
      "Don’t ever tell anybody anything. If you do, you start missing everybody.",
    ],
    comments: [{ page: 50, text: "Holden is annoying but honest." }],
    cover: "https://covers.openlibrary.org/b/id/8235266-L.jpg",
    state: BookState.Read,
    progressPage: 214,
    favourite: false,
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    initDate: [new Date("2024-06-01")],
    endDate: [],
    description: "The obsession of Captain Ahab with the white whale.",
    quotes: ["Call me Ishmael."],
    comments: [{ page: 33, text: "Opening line is iconic." }],
    cover: "https://covers.openlibrary.org/b/id/7222256-L.jpg",
    state: BookState.Reading,
    progressPage: 120,
    favourite: false,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    initDate: [new Date("2023-02-01")],
    endDate: [new Date("2023-02-10")],
    description: "A tragic story of love and the American Dream.",
    valoration: 4,
    review: "Sad but beautifully written.",
    quotes: ["So we beat on, boats against the current..."],
    comments: [{ page: 170, text: "Gatsby’s obsession is tragic." }],
    cover: "https://covers.openlibrary.org/b/id/7222241-L.jpg",
    state: BookState.Read,
    progressPage: 180,
    favourite: false,
  },
  {
    title: "Harry Potter and the Philosopher’s Stone",
    author: "J.K. Rowling",
    initDate: [new Date("2022-12-01")],
    endDate: [new Date("2022-12-15")],
    description: "The first Harry Potter book.",
    valoration: 5,
    review: "Magical and nostalgic.",
    quotes: ["It does not do to dwell on dreams and forget to live."],
    comments: [{ page: 50, text: "Introduction to the magical world." }],
    cover: "https://covers.openlibrary.org/b/id/7984916-L.jpg",
    state: BookState.Read,
    progressPage: 223,
    favourite: true,
    saga: "Harry Potter",
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    initDate: [new Date("2023-01-05")],
    endDate: [new Date("2023-01-20")],
    description: "The second Harry Potter book.",
    valoration: 4,
    review: "Darker, still fun.",
    quotes: ["It is our choices, Harry, that show what we truly are."],
    comments: [{ page: 150, text: "Dobby is hilarious and tragic." }],
    cover: "https://covers.openlibrary.org/b/id/7984917-L.jpg",
    state: BookState.Read,
    progressPage: 251,
    favourite: true,
    saga: "Harry Potter",
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    initDate: [],
    endDate: [],
    description: "The third Harry Potter book.",
    quotes: ["Happiness can be found even in the darkest of times."],
    comments: [{ page: 150, text: "First time we see the Patronus spell." }],
    cover: "https://covers.openlibrary.org/b/id/7984918-L.jpg",
    state: BookState.Pendant,
    progressPage: 0,
    favourite: false,
    saga: "Harry Potter",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    initDate: [new Date("2021-07-01")],
    endDate: [new Date("2021-07-10")],
    description: "A philosophical story about destiny and dreams.",
    valoration: 3,
    review: "Inspirational but overrated.",
    quotes: ["When you want something, all the universe conspires..."],
    comments: [{ page: 70, text: "Too mystical for me." }],
    cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    state: BookState.Read,
    progressPage: 197,
    favourite: false,
  },
  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    initDate: [new Date("2020-08-01")],
    endDate: [new Date("2020-08-02")],
    description: "A poetic tale of innocence, love, and loss.",
    valoration: 5,
    review: "Beautiful in its simplicity.",
    quotes: ["It is only with the heart that one can see rightly."],
    comments: [{ page: 20, text: "Makes me cry every time." }],
    cover: "https://covers.openlibrary.org/b/id/7222276-L.jpg",
    state: BookState.Read,
    progressPage: 96,
    favourite: true,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    initDate: [new Date("2022-05-10")],
    endDate: [new Date("2022-05-22")],
    description: "A thriller full of puzzles, art, and conspiracies.",
    valoration: 4,
    review: "Fast-paced and entertaining.",
    quotes: ["Everything is possible. The impossible just takes longer."],
    comments: [{ page: 230, text: "Kept me hooked with puzzles." }],
    cover: "https://covers.openlibrary.org/b/id/8270664-L.jpg",
    state: BookState.Read,
    progressPage: 454,
    favourite: false,
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    initDate: [],
    endDate: [],
    description: "A dystopian vision of a controlled society.",
    quotes: ["Words can be like X-rays if you use them properly."],
    comments: [{ page: 15, text: "On my list to read." }],
    cover: "https://covers.openlibrary.org/b/id/7222231-L.jpg",
    state: BookState.Pendant,
    progressPage: 0,
    favourite: false,
  },
  {
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    initDate: [new Date("2025-01-15")],
    endDate: [],
    description: "The story of Kvothe, a legendary figure.",
    quotes: ["Words are pale shadows of forgotten names."],
    comments: [
      { page: 50, text: "Kvothe’s childhood is so tragic." },
      { page: 200, text: "The writing style is so lyrical." },
    ],
    cover: "https://covers.openlibrary.org/b/id/8235116-L.jpg",
    state: BookState.Reading,
    progressPage: 200,
    favourite: true,
    saga: "The Kingkiller Chronicle",
  },
];
